version: '3'
services:
  db:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set the root password
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql  # Use the environment variable for the data directory
    restart: unless-stopped  # Optional: Ensures the container restarts automatically

  phpmyadmin:
    image: phpmyadmin
    container_name: my-phpmyadmin
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    environment:
      PMA_HOST: db  # Link phpMyAdmin to the MySQL container
    depends_on:
      - db  # Ensure the MySQL container starts first
    restart: unless-stopped  # Optional: Ensures the container restarts automatically